---
apiVersion: v1
kind: Service
metadata:
  name: hello-greeter-k8s-fe-service
spec:
  selector:
    app: hello-greeter-k8s-fe
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: LoadBalancer